# Generated by Django 2.1.3 on 2018-11-15 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prior_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inactive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('marketsymbol', models.CharField(max_length=32)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prior_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price_52_weeks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price_52_weeks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('logo', models.ImageField(upload_to='')),
                ('inactive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StocksIndexed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockindex_app.Index')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockindex_app.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='observations',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockindex_app.Stock'),
        ),
    ]
