# Generated by Django 2.1.3 on 2018-11-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockindex_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='change_mktcap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='current_mktcap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='high_mktcap_52_weeks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='low_mktcap_52_weeks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='prior_mktcap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='shares_outstanding',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
