# Generated by Django 2.1.3 on 2018-11-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockindex_app', '0002_auto_20181116_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='prior_value',
            new_name='prior_close_value',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='current_mktcap',
            new_name='market_cap',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='prior_price',
            new_name='prior_close_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='change_mktcap',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='high_mktcap_52_weeks',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='low_mktcap_52_weeks',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='market',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='marketsymbol',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='prior_mktcap',
        ),
        migrations.AddField(
            model_name='observations',
            name='shares_outstanding',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='high_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='low_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observations',
            name='observation_date',
            field=models.DateTimeField(),
        ),
    ]
