# Generated by Django 2.1.3 on 2018-11-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockindex_app', '0004_auto_20181120_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
