# Generated by Django 2.1.3 on 2018-11-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockindex_app', '0005_auto_20181120_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocksindexed',
            old_name='index_id',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='stocksindexed',
            old_name='stock_id',
            new_name='stock',
        ),
    ]
