# Generated by Django 2.1.3 on 2018-11-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockindex_app', '0006_auto_20181120_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observations',
            old_name='stock_id',
            new_name='stock',
        ),
    ]
