# Generated by Django 2.1.3 on 2018-12-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockindex_app', '0009_auto_20181226_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='high_market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='low_market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
