# Generated by Django 2.1.3 on 2018-12-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockindex_app', '0010_auto_20181226_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexObservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateTimeField(null=True)),
                ('open_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('high_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('low_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('close_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockindex_app.Index')),
            ],
        ),
    ]
