# Generated by Django 2.1.3 on 2018-12-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockindex_app', '0011_indexobservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexobservations',
            name='close_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='indexobservations',
            name='high_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='indexobservations',
            name='low_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='indexobservations',
            name='open_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
