# Generated by Django 2.1.3 on 2018-12-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockindex_app', '0012_auto_20181227_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='high_price_52_weeks',
            new_name='high_value_52_weeks',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='low_price_52_weeks',
            new_name='low_value_52_weeks',
        ),
    ]
